(function(window){

	function EngineNotificationsEnum(){}
  
	EngineNotificationsEnum.APPLICATIONVIEW_CHANGED_NOTIFICATION   = "APPLICATIONVIEW_CHANGED_NOTIFICATION";
	EngineNotificationsEnum.COUNTER_CHANGED_NOTIFICATION           = "COUNTER_CHANGED_NOTIFICATION";
	EngineNotificationsEnum.VALUES_CHANGED_NOTIFICATION            = "VALUES_CHANGED_NOTIFICATION";
	EngineNotificationsEnum.INITIALIZATION_COMPLETED_NOTIFICATION  = "INITIALIZATION_COMPLETED_NOTIFICATION";
	EngineNotificationsEnum.NO_MORE_CREDITS_NOTIFICATION           = "NO_CREDITS_NOTIFICATION";
	EngineNotificationsEnum.NEXT_AUTOPLAY_EXTRA_OPTION_NOTIFICATION= "NEXT_AUTOPLAY_EXTRA_OPTION_NOTIFICATION";
	EngineNotificationsEnum.PREV_AUTOPLAY_EXTRA_OPTION_NOTIFICATION= "PREV_AUTOPLAY_EXTRA_OPTION_NOTIFICATION";
	EngineNotificationsEnum.NEXT_SPEED_NOTIFICATION                = "NEXT_SPEED_NOTIFICATION";
	
	EngineNotificationsEnum.BAR_HELP_CLICK_NOTIFICATION            = "BAR_HELP_CLICK_NOTIFICATION";
	EngineNotificationsEnum.AUTOPLAY_START_NOTIFICATION            = "AUTOPLAY_START_NOTIFICATION";
	EngineNotificationsEnum.AUTOPLAY_MODIFIED_NOTIFICATION         = "AUTOPLAY_MODIFIED_NOTIFICATION";
	EngineNotificationsEnum.AUTOPLAY_STOP_NOTIFICATION             = "AUTOPLAY_STOP_NOTIFICATION";
	EngineNotificationsEnum.LOG_NOTIFICATION                       = "LOG_NOTIFICATION";

	window.EngineNotificationsEnum = EngineNotificationsEnum;

}(window));